import {React, useState} from "react";
import styled from "styled-components";

const LandingPageButton = (props) => {
const [clicked, setClicked] = useState(false);


const handleButton = (props) => {
  props.clickHandler()

  setClicked(current => !current)
}

  return (
    <Button onClick={() => { 
      handleButton();
    }} clicked={clicked}>
      <span>Get to know me</span>
    </Button>
  );
};

const Button = styled.button`
  align-items: center;
  appearance: none;
  background-color: #FCFCFD;
  border-radius: 4px;
  border-width: 0;
  box-shadow: rgba(45, 35, 66, 0.4) 0 2px 4px,rgba(45, 35, 66, 0.3) 0 7px 13px -3px,#D6D6E7 0 -3px 0 inset;
  box-sizing: border-box;
  color: #36395A;
  cursor: pointer;
  display: inline-flex;
  height: 48px;
  justify-content: center;
  line-height: 1;
  list-style: none;
  overflow: hidden;
  padding-left: 16px;
  padding-right: 16px;
  position: relative;
  text-align: left;
  text-decoration: none;
  transition: box-shadow .15s,transform .15s;
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
  white-space: nowrap;
  will-change: box-shadow,transform;
  font-size: 18px;

  ${props => {
    if(props.clicked) {
      return `
      animation:slide-out-top .5s cubic-bezier(.55,.085,.68,.53) both
      `
    }
  }}

${props => {
  if(props.clicked) {
    return `
    /* ----------------------------------------------
 * Generated by Animista on 2022-6-24 15:33:37
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@keyframes slide-out-top{0%{transform:translateY(0);opacity:1}100%{transform:translateY(-1000px);opacity:0}}
    `
  }
}}

&:focus {
  box-shadow: #D6D6E7 0 0 0 1.5px inset, rgba(45, 35, 66, 0.4) 0 2px 4px, rgba(45, 35, 66, 0.3) 0 7px 13px -3px, #D6D6E7 0 -3px 0 inset;
}

&:hover {
  box-shadow: rgba(45, 35, 66, 0.4) 0 4px 8px, rgba(45, 35, 66, 0.3) 0 7px 13px -3px, #D6D6E7 0 -3px 0 inset;
  transform: translateY(-2px);
}

&:active {
  box-shadow: #D6D6E7 0 3px 7px inset;
  transform: translateY(2px);
  opacity: 0;
  animation:slide-out-top .2s cubic-bezier(.55,.085,.68,.53) both;
  animation-fill-mode: forwards;
}
@keyframes slide-out-top{0%{transform:translateY(0);opacity:1}100%{transform:translateY(-1000px);opacity:0}}

  & span {
    font-family: 'Open Sans', sans-serif;
    font-size: 32px;
    font-weight: 400;
  }
`;

export default LandingPageButton;
